console.log("Завдання: 9 ==============================");

function task9() {
  function fetchWithError(error) {
    return Promise.reject(new Error(error));
  }

  const errorMessage = "Помилка при з'єднанні з сервером";
  fetchWithError(errorMessage)
    .then((value) => {
      console.log(value);
    })
    .catch((error) => {
      console.log(error);
    });
  // Створюємо функцію fetchWithError, яка симулює помилку при запиті до сервера.
  // Створюємо константу errorMessage в яку записуємо рядок "Помилка при з'єднанні з сервером"
  // Використовуємо Promise.reject(errorMessage) для створення вже відхиленого промісу.
  // Викликаємо функцію fetchWithError
  // Якщо проміс виконаний успішно виводимо в консоль дані які він повертає
  // Якщо проміс виконаний з помилкою виводимо в консоль помилку
}

// Викликаємо функцію task10
task9();
